### ISSUE TITLE
Use Vue 3 with Vite instead of Nuxt 2

### ISSUE THREAD

**Issue by larsrickert** [philippabele/nursing-home-volunteer#17]
We are currently using Nuxt 2 which still uses Vue 2 under the hood. I would like to use the latest version [vue 3](https://v3.vuejs.org/) with [vite](https://vitejs.dev/) This would enable several benefits:

- much faster development server start time
- faster builds
- smaller bundle/build size
- more modern vue features (especially for future developers it would be a good idea to use vue 3 because they will not likely learn vue 2 then)
- simpler components due to vue 3 [<script setup>](https://v3.vuejs.org/api/sfc-script-setup.html#basic-syntax)
- better typescript support
- more explicit coding, e.g. in nuxt components get imported automatically which might make development easier but I'm am a fan of coding explicitly what the app should do
- better linting which prevents errors (this benefit is caused by the more explizit coding)

Some other notes:
- I have a template app for vue 3 with vite so the transition from our current nuxt project will not take much time
- I will have to check if [bootstrap vue](https://bootstrap-vue.org/) works with vite

What are your thoughts on this?

**Comment by philippabele** [comment]
Ok. Let's give it a try and switch to Vue3 with Vite.
