### ISSUE TITLE
Add sub section on how to set up GitHub Actions for Latex

### ISSUE THREAD

**Issue by philippabele** [philippabele/nursing-home-volunteer#37]

**Comment by philippabele** [comment]
@larsrickert see it as an amendment for future students. This will help future students for this or comparable projects to get up to speed faster.

**Comment by larsrickert** [comment]
> @larsrickert see it as an amendment for future students. This will help future students for this or comparable projects to get up to speed faster.

Alright, but it should not be included in the latex documentation then. Are you fine with including this part in `docs/README.md`?
