### ISSUE TITLE
Write documentation about project structure

### ISSUE THREAD

**Issue by larsrickert** [philippabele/nursing-home-volunteer#39]
Documentation should include the following:

Frontend:
- Folder structure
- instructions how to install/start/build the frontend locally
- screenshots of the frontend
- how it interacts with the backend

Backend:
- Strapi GUI (with screenshots)
- Structure of the blog post content type
- How to install/start/build the backend locally

**Comment by philippabele** [comment]
@larsrickert I finished my first review on this chapter, but there is a merge conflict. Please take care about it and merge the branch.
