### ISSUE TITLE
Change link in GitHub "About" section to https

### ISSUE THREAD

**Issue by larsrickert** [philippabele/nursing-home-volunteer#40]
Currently the linked frontend in the "About" section on the [repo start page](https://github.com/philippabele/nursing-home-volunteer) points to the insecure http version of the site.

Please update the link to: https://nursing-home-volunteer-app.herokuapp.com/

**Comment by philippabele** [comment]
@larsrickert due to the change of the hosting set up, I will close this issue and remove the link from the project site.
